In [8]:
import pandas as pd
import numpy as np
import plotly.express as px

np.random.seed(42)
px.defaults.template = "plotly_white"

months = pd.date_range("2024-01-01", periods=6, freq="MS")
regions = ["North", "South", "East"]
products = ["A", "B"]

rows = []

for month in months:
    for region in regions:
        for product in products:
            sales = np.random.randint(80, 220)
            customers = np.random.randint(20, 90)
            units = np.random.randint(10, 70)
            
            rows.append([month, region, product, sales, customers, units])

df_plotly = pd.DataFrame(
    rows,
    columns=["month", "region", "product", "sales", "customers", "units"]
)

df_plotly["month_name"] = df_plotly["month"].dt.strftime("%b")
df_plotly.head()

       month region product  sales  customers  units month_name
0 2024-01-01  North       A    182         71     38        Jan
1 2024-01-01  North       B     94         80     30        Jan
2 2024-01-01  South       A    182         43     12        Jan
3 2024-01-01  South       B    132         21     33        Jan
4 2024-01-01   East       A    117         21     69        Jan

In [19]:
monthly_sales = df_plotly.groupby("month", as_index = False)[['customers', 'units', 'sales']].sum()
monthly_sales

       month  customers  units  sales
0 2024-01-01        288    203    807
1 2024-02-01        347    289    810
2 2024-03-01        380    151    831
3 2024-04-01        344    202    855
4 2024-05-01        281    207    934
5 2024-06-01        252    262    796

In [22]:
monthly_sales = (
    df_plotly.groupby("month", as_index=False)["sales"]
             .sum()
)

monthly_sales

       month  sales
0 2024-01-01    807
1 2024-02-01    810
2 2024-03-01    831
3 2024-04-01    855
4 2024-05-01    934
5 2024-06-01    796

In [29]:
fig = px.line(
    monthly_sales,
    x="month",
    y="sales",
    markers=True,
    title="Monthly Total Sales"
)

fig.update_layout(
  
    xaxis_title="Month",
    yaxis_title="Sales"
)

fig.show()